on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@v4
      - id: build
        run: |
          out_path=$(nix build -L .#example --accept-flake-config --print-out-paths)
          drv=$(nix path-info --derivation .#example)
          drvName=$(basename "$drv")
          hash=$(nix hash path "$out_path")
          {
            echo "out-path=$out_path" 
            echo "drv-name=$drvName"
            echo "hash=$hash"
          } >> "$GITHUB_OUTPUT"
      - uses: actions/attest@v2
        with:
          subject-name: ${{ steps.build.outputs.out-path }}
          subject-digest: ${{ steps.build.outputs.hash }} 
          predicate-type: https://slsa.dev/provenance/v1
          predicate-path: /nix/var/nix/provenance/${{ steps.build.outputs.drv-name }}.slsa.json
