on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      path-info: ${{ steps.build.outputs.path-info }}
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@v4
      - id: build
        env:
          installable: .#example^*
        run: |
          set -o pipefail
          pathInfo=$(nix --accept-flake-config build --print-build-logs --print-out-paths "$installable" | xargs nix path-info --json | jq -c 'to_entries')
          echo "path-info=$pathInfo" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v4
        with:
          name: provenance
          path: /nix/var/nix/provenance/*
  attest:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      # TODO: Make a custom action for this. We want to have a list of subject digests. One for
      # each output. We can't do that with the current action. So we just assume that there
      # is only one output.
      - uses: actions/download-artifact@v4
        with:
          name: provenance
      - id: convert-digest
        run: echo "digest=sha256:$(nix hash convert --to base16 "$narHash")" >> "$GITHUB_OUTPUT"
        env:
          narHash: ${{ fromJson(needs.build.outputs.path-info)[0].value.narHash }}
      # NOTE: we're throwing away the subjects here
      - run: |
          jq '.predicate' "$statementPath" > predicate.slsa.json
        env:
          statementPath: "./${{fromJson(needs.build.outputs.path-info)[0].value.deriver}}.slsa.json"
      - uses: actions/attest@v2
        with:
          subject-name: ${{ fromJson(needs.build.outputs.path-info)[0].key }}
          # NOTE: This is the NAR hash, not the SRI hash. So a verifier should
          # get the NAR serialisation of the nix store path
          # TODO: Should we name NAR files differently?
          subject-digest: ${{ steps.convert-digest.outputs.digest }} 
          predicate-type: https://slsa.dev/provenance/v1
          predicate-path: predicate.slsa.json
